language: node_js
node_js:
- '8'
sudo: false
before_deploy:
- node run.js > platform.json
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "*.tar.gz"
    - platform.json
  file_glob: true
  skip_cleanup: true
  name: $TRAVIS_TAG
  on:
    tags: true
